/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known/jwks[.]json'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as AuthGithubRouteImport } from './routes/auth.github'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as ServersServerIdRouteImport } from './routes/servers.$serverId'
import { Route as ServersNewRouteImport } from './routes/servers.new'
import { Route as DotwellKnownOauthProtectedResourceSplatRouteImport } from './routes/[.]well-known/oauth-protected-resource.$'
import { Route as ApiPublicCronHealthRouteImport } from './routes/api/public/cron/health'
import { Route as ApiPublicMcpServerIdRouteImport } from './routes/api/public/mcp/$serverId'
import { Route as ApiPublicOauthAuthorizeRouteImport } from './routes/api/public/oauth/authorize'
import { Route as ApiPublicOauthMetadataRouteImport } from './routes/api/public/oauth/metadata'
import { Route as ApiPublicOauthRegisterRouteImport } from './routes/api/public/oauth/register'
import { Route as ApiPublicOauthRevokeRouteImport } from './routes/api/public/oauth/revoke'
import { Route as ApiPublicOauthTokenRouteImport } from './routes/api/public/oauth/token'
import { Route as ApiPublicOauthUpstreamCallbackRouteImport } from './routes/api/public/oauth/upstream-callback'
import { Route as ApiPublicTelemetryV1EventsRouteImport } from './routes/api/public/telemetry/v1/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AuthRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersNewRoute = ServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceSplatRoute =
  DotwellKnownOauthProtectedResourceSplatRouteImport.update({
    id: '/.well-known/oauth-protected-resource/$',
    path: '/.well-known/oauth-protected-resource/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHealthRoute = ApiPublicCronHealthRouteImport.update({
  id: '/api/public/cron/health',
  path: '/api/public/cron/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpServerIdRoute = ApiPublicMcpServerIdRouteImport.update({
  id: '/api/public/mcp/$serverId',
  path: '/api/public/mcp/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthAuthorizeRoute = ApiPublicOauthAuthorizeRouteImport.update({
  id: '/api/public/oauth/authorize',
  path: '/api/public/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthMetadataRoute = ApiPublicOauthMetadataRouteImport.update({
  id: '/api/public/oauth/metadata',
  path: '/api/public/oauth/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthRegisterRoute = ApiPublicOauthRegisterRouteImport.update({
  id: '/api/public/oauth/register',
  path: '/api/public/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthRevokeRoute = ApiPublicOauthRevokeRouteImport.update({
  id: '/api/public/oauth/revoke',
  path: '/api/public/oauth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthTokenRoute = ApiPublicOauthTokenRouteImport.update({
  id: '/api/public/oauth/token',
  path: '/api/public/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthUpstreamCallbackRoute =
  ApiPublicOauthUpstreamCallbackRouteImport.update({
    id: '/api/public/oauth/upstream-callback',
    path: '/api/public/oauth/upstream-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelemetryV1EventsRoute =
  ApiPublicTelemetryV1EventsRouteImport.update({
    id: '/api/public/telemetry/v1/events',
    path: '/api/public/telemetry/v1/events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/operators': typeof OperatorsRoute
  '/telemetry': typeof TelemetryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/auth/github': typeof AuthGithubRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/api/public/cron/health': typeof ApiPublicCronHealthRoute
  '/api/public/mcp/$serverId': typeof ApiPublicMcpServerIdRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/metadata': typeof ApiPublicOauthMetadataRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
  '/api/public/oauth/revoke': typeof ApiPublicOauthRevokeRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/oauth/upstream-callback': typeof ApiPublicOauthUpstreamCallbackRoute
  '/api/public/telemetry/v1/events': typeof ApiPublicTelemetryV1EventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/operators': typeof OperatorsRoute
  '/telemetry': typeof TelemetryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/auth/github': typeof AuthGithubRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/api/public/cron/health': typeof ApiPublicCronHealthRoute
  '/api/public/mcp/$serverId': typeof ApiPublicMcpServerIdRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/metadata': typeof ApiPublicOauthMetadataRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
  '/api/public/oauth/revoke': typeof ApiPublicOauthRevokeRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/oauth/upstream-callback': typeof ApiPublicOauthUpstreamCallbackRoute
  '/api/public/telemetry/v1/events': typeof ApiPublicTelemetryV1EventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/operators': typeof OperatorsRoute
  '/telemetry': typeof TelemetryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/auth/github': typeof AuthGithubRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/api/public/cron/health': typeof ApiPublicCronHealthRoute
  '/api/public/mcp/$serverId': typeof ApiPublicMcpServerIdRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/metadata': typeof ApiPublicOauthMetadataRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
  '/api/public/oauth/revoke': typeof ApiPublicOauthRevokeRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/oauth/upstream-callback': typeof ApiPublicOauthUpstreamCallbackRoute
  '/api/public/telemetry/v1/events': typeof ApiPublicTelemetryV1EventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/operators'
    | '/telemetry'
    | '/.well-known/jwks.json'
    | '/.well-known/oauth-authorization-server'
    | '/auth/github'
    | '/oauth/consent'
    | '/servers/$serverId'
    | '/servers/new'
    | '/.well-known/oauth-protected-resource/$'
    | '/api/public/cron/health'
    | '/api/public/mcp/$serverId'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/metadata'
    | '/api/public/oauth/register'
    | '/api/public/oauth/revoke'
    | '/api/public/oauth/token'
    | '/api/public/oauth/upstream-callback'
    | '/api/public/telemetry/v1/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/operators'
    | '/telemetry'
    | '/.well-known/jwks.json'
    | '/.well-known/oauth-authorization-server'
    | '/auth/github'
    | '/oauth/consent'
    | '/servers/$serverId'
    | '/servers/new'
    | '/.well-known/oauth-protected-resource/$'
    | '/api/public/cron/health'
    | '/api/public/mcp/$serverId'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/metadata'
    | '/api/public/oauth/register'
    | '/api/public/oauth/revoke'
    | '/api/public/oauth/token'
    | '/api/public/oauth/upstream-callback'
    | '/api/public/telemetry/v1/events'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/operators'
    | '/telemetry'
    | '/.well-known/jwks.json'
    | '/.well-known/oauth-authorization-server'
    | '/auth/github'
    | '/oauth/consent'
    | '/servers/$serverId'
    | '/servers/new'
    | '/.well-known/oauth-protected-resource/$'
    | '/api/public/cron/health'
    | '/api/public/mcp/$serverId'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/metadata'
    | '/api/public/oauth/register'
    | '/api/public/oauth/revoke'
    | '/api/public/oauth/token'
    | '/api/public/oauth/upstream-callback'
    | '/api/public/telemetry/v1/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OperatorsRoute: typeof OperatorsRoute
  TelemetryRoute: typeof TelemetryRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersNewRoute: typeof ServersNewRoute
  DotwellKnownOauthProtectedResourceSplatRoute: typeof DotwellKnownOauthProtectedResourceSplatRoute
  ApiPublicCronHealthRoute: typeof ApiPublicCronHealthRoute
  ApiPublicMcpServerIdRoute: typeof ApiPublicMcpServerIdRoute
  ApiPublicOauthAuthorizeRoute: typeof ApiPublicOauthAuthorizeRoute
  ApiPublicOauthMetadataRoute: typeof ApiPublicOauthMetadataRoute
  ApiPublicOauthRegisterRoute: typeof ApiPublicOauthRegisterRoute
  ApiPublicOauthRevokeRoute: typeof ApiPublicOauthRevokeRoute
  ApiPublicOauthTokenRoute: typeof ApiPublicOauthTokenRoute
  ApiPublicOauthUpstreamCallbackRoute: typeof ApiPublicOauthUpstreamCallbackRoute
  ApiPublicTelemetryV1EventsRoute: typeof ApiPublicTelemetryV1EventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof AuthRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/new': {
      id: '/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof ServersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/$': {
      id: '/.well-known/oauth-protected-resource/$'
      path: '/.well-known/oauth-protected-resource/$'
      fullPath: '/.well-known/oauth-protected-resource/$'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/health': {
      id: '/api/public/cron/health'
      path: '/api/public/cron/health'
      fullPath: '/api/public/cron/health'
      preLoaderRoute: typeof ApiPublicCronHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp/$serverId': {
      id: '/api/public/mcp/$serverId'
      path: '/api/public/mcp/$serverId'
      fullPath: '/api/public/mcp/$serverId'
      preLoaderRoute: typeof ApiPublicMcpServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize': {
      id: '/api/public/oauth/authorize'
      path: '/api/public/oauth/authorize'
      fullPath: '/api/public/oauth/authorize'
      preLoaderRoute: typeof ApiPublicOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/metadata': {
      id: '/api/public/oauth/metadata'
      path: '/api/public/oauth/metadata'
      fullPath: '/api/public/oauth/metadata'
      preLoaderRoute: typeof ApiPublicOauthMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/register': {
      id: '/api/public/oauth/register'
      path: '/api/public/oauth/register'
      fullPath: '/api/public/oauth/register'
      preLoaderRoute: typeof ApiPublicOauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/revoke': {
      id: '/api/public/oauth/revoke'
      path: '/api/public/oauth/revoke'
      fullPath: '/api/public/oauth/revoke'
      preLoaderRoute: typeof ApiPublicOauthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/token': {
      id: '/api/public/oauth/token'
      path: '/api/public/oauth/token'
      fullPath: '/api/public/oauth/token'
      preLoaderRoute: typeof ApiPublicOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/upstream-callback': {
      id: '/api/public/oauth/upstream-callback'
      path: '/api/public/oauth/upstream-callback'
      fullPath: '/api/public/oauth/upstream-callback'
      preLoaderRoute: typeof ApiPublicOauthUpstreamCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry/v1/events': {
      id: '/api/public/telemetry/v1/events'
      path: '/api/public/telemetry/v1/events'
      fullPath: '/api/public/telemetry/v1/events'
      preLoaderRoute: typeof ApiPublicTelemetryV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthGithubRoute: typeof AuthGithubRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGithubRoute: AuthGithubRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OperatorsRoute: OperatorsRoute,
  TelemetryRoute: TelemetryRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  OauthConsentRoute: OauthConsentRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ServersNewRoute: ServersNewRoute,
  DotwellKnownOauthProtectedResourceSplatRoute:
    DotwellKnownOauthProtectedResourceSplatRoute,
  ApiPublicCronHealthRoute: ApiPublicCronHealthRoute,
  ApiPublicMcpServerIdRoute: ApiPublicMcpServerIdRoute,
  ApiPublicOauthAuthorizeRoute: ApiPublicOauthAuthorizeRoute,
  ApiPublicOauthMetadataRoute: ApiPublicOauthMetadataRoute,
  ApiPublicOauthRegisterRoute: ApiPublicOauthRegisterRoute,
  ApiPublicOauthRevokeRoute: ApiPublicOauthRevokeRoute,
  ApiPublicOauthTokenRoute: ApiPublicOauthTokenRoute,
  ApiPublicOauthUpstreamCallbackRoute: ApiPublicOauthUpstreamCallbackRoute,
  ApiPublicTelemetryV1EventsRoute: ApiPublicTelemetryV1EventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
