/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ServersServerIdRouteImport } from './routes/servers.$serverId'
import { Route as ServersNewRouteImport } from './routes/servers.new'
import { Route as ApiPublicMcpServerIdRouteImport } from './routes/api/public/mcp/$serverId'
import { Route as ApiPublicOauthAuthorizeRouteImport } from './routes/api/public/oauth/authorize'
import { Route as ApiPublicOauthRegisterRouteImport } from './routes/api/public/oauth/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersNewRoute = ServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpServerIdRoute = ApiPublicMcpServerIdRouteImport.update({
  id: '/api/public/mcp/$serverId',
  path: '/api/public/mcp/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthAuthorizeRoute = ApiPublicOauthAuthorizeRouteImport.update({
  id: '/api/public/oauth/authorize',
  path: '/api/public/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthRegisterRoute = ApiPublicOauthRegisterRouteImport.update({
  id: '/api/public/oauth/register',
  path: '/api/public/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/api/public/mcp/$serverId': typeof ApiPublicMcpServerIdRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/api/public/mcp/$serverId': typeof ApiPublicMcpServerIdRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/api/public/mcp/$serverId': typeof ApiPublicMcpServerIdRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/servers/$serverId'
    | '/servers/new'
    | '/api/public/mcp/$serverId'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/servers/$serverId'
    | '/servers/new'
    | '/api/public/mcp/$serverId'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/register'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/servers/$serverId'
    | '/servers/new'
    | '/api/public/mcp/$serverId'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersNewRoute: typeof ServersNewRoute
  ApiPublicMcpServerIdRoute: typeof ApiPublicMcpServerIdRoute
  ApiPublicOauthAuthorizeRoute: typeof ApiPublicOauthAuthorizeRoute
  ApiPublicOauthRegisterRoute: typeof ApiPublicOauthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/new': {
      id: '/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof ServersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp/$serverId': {
      id: '/api/public/mcp/$serverId'
      path: '/api/public/mcp/$serverId'
      fullPath: '/api/public/mcp/$serverId'
      preLoaderRoute: typeof ApiPublicMcpServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize': {
      id: '/api/public/oauth/authorize'
      path: '/api/public/oauth/authorize'
      fullPath: '/api/public/oauth/authorize'
      preLoaderRoute: typeof ApiPublicOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/register': {
      id: '/api/public/oauth/register'
      path: '/api/public/oauth/register'
      fullPath: '/api/public/oauth/register'
      preLoaderRoute: typeof ApiPublicOauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ServersNewRoute: ServersNewRoute,
  ApiPublicMcpServerIdRoute: ApiPublicMcpServerIdRoute,
  ApiPublicOauthAuthorizeRoute: ApiPublicOauthAuthorizeRoute,
  ApiPublicOauthRegisterRoute: ApiPublicOauthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
